### ISSUE TITLE
Different results reading with opts and reading with data_readers

### ISSUE THREAD

**Issue by danieldroit** [henryw374/time-literals#5]
`(edn/read-string {:readers time-literals.read-write/tags} "#time/zoned-date-time \"2022-01-01T16:14:34.447Z\"")`

produces : `java.time.ZonedDateTime 2022-01-01T16:14:34.447Z` as expected

but:

`(edn/read-string {:readers *data-readers*} "#time/zoned-date-time \"2022-01-01T16:14:34.447Z\"")`

produces Clojure list:

`(. java.time.ZonedDateTime parse "2022-01-01T16:14:34.447Z")`

![image](https://user-images.githubusercontent.com/26548638/155424727-04e68f34-6e3d-4539-8e04-4e508537dba8.png)

**Comment by henryw374** [comment]
This was fixed as per #3
